- name: Ansible playbook to create all the Roboshop Project Jobs in Jenkins Server.
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - APP-SETUP-WITH-ANSIBLE
      - Infrastructure
    pipeline_jobs:
      - { jobName: "roboshop", folderName: "APP-SETUP-WITH-ANSIBLE", repoName: "roboshop-ansible", fileName: "Jenkinsfile" }
      - { jobName: "cart", folderName: "Infrastructure", repoName: "cart-infra", fileName: "Jenkinsfile" }
