- name: Ansible playbook to create all the Roboshop Project Jobs in Jenkins Server.
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - demo
    pipeline_jobs:
      - { jobName: "sample3", folderName: "demo", repoName: "learning-jenkins"}
      - { jobName: "sample3", folderName: "demo", repoName: "learning-something"}